class Settings:
    screen_width, screen_height = 1000, 800
    bg_color = 135, 206, 250
    player_right_image = 'images/right.bmp'
    player_left_image = 'images/left.bmp'
    player_speed = 2
    player_jump_high = 150
    player_jump_speed = 1
    brick_color = 101, 67, 33
    brick_width = 300
    brick_height = 10
    score_image = 'images/score.bmp'
    sb_color = 0, 0, 0
    monster_image = 'images/monster.bmp'
    monster_speed = 0.7
    monster_jump_speed = 0.7
    monster_time = 1
    door_image = 'images/door.bmp'
    door_opened_image = 'images/door_opened.bmp'
    max_score = 10
    max_level = 3
    bg_mp3 = 'mp3/bg_mp3.mp3'
    game_over_sound = 'mp3/game_over.mp3'
    score_sound = 'mp3/score.mp3'
    win_sound = 'mp3/win.mp3'
    time = 60
